name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: ./build-win.ps1
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: sudo apt install -y clang
      - run: ./build-linux.sh
